default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rpg_annotator_api_development

test:
  <<: *default
  database: rpg_annotator_api_test

production: &production
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

cable:
  <<: *production

cache:
  <<: *production

queue:
  <<: *production